### ISSUE TITLE
Extend explore-local script. Add FairSale and realistic bids

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-subgraph#41]
## Detailed Description

Create a Fairsale Sale and make some bids, best to use the realistic bid set.

## Context

If started with `yarn explore-local` a local version of the subgraph with some example sales is created. This can then be explored by connecting the interface to the local version.

## Possible Implementation

Has to be added to explore-local.ts

**Comment by martinkrung** [comment]
Comment from @adamazad on this:

"Requires updating the contract architecture to move forward with this card" 

What does this mean?

**Comment by adamazad** [comment]
Since #47 is implemented, the next step would be this.
