### ISSUE TITLE
Implement decodeOrder and encoodeOrder for FairSale's subgraph

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-subgraph#42]
Data for Fairsale  is stored on chain in a compressed datastructur and we have trouble reading this.

**Comment by adamazad** [comment]
Great progress here to be frank using [`ethereum.Value`](https://thegraph.com/docs/assemblyscript-api#ethereum-api)

**Comment by adamazad** [comment]
Implemented via #47
