### ISSUE TITLE
Rebase the software version to 0.1.x

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-subgraph#51]
As a part of a new relesase protocol

**Comment by adamazad** [comment]
#### Procedure

1. Rename every `v2/<branch-name>` branch to `<branch-name>`
2. Starting using `feature/<branch-name>` for features
3. Starting using `bug/<branch-name>` for bug

**Comment by adamazad** [comment]
@martinkrung, how do you want to go about rebasing the branches without being destructed? I suggested the above outline.

**Comment by martinkrung** [comment]
@adamazad 

I think I don't understand completely your question. But using v names in branch is not best practices and you want to clean that up?

Next Version is 0.1.1!

I would make a **next** branch and merge this to main on release, then recreate the **next** branch? Like in the smart contract repo?
