### ISSUE TITLE
Prepare for 0.1.1 release

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-subgraph#80]
- Summary/Highlights
- Docs
- Changes logs

**Comment by rossneilson** [comment]
Thanks for adding and tracking this work. 
This should be a high priority over the next week as we prepare for MVP release.

If you could also track any major changes that will be needed in the UI from current `next` release to the full 0.1.1 release that would be very helpful and help us faster release MVP.

The full MVP release will be after audit (couple of weeks) however we are also planning internal testing within DXdao so are aiming to release ASAP.

**Comment by adamazad** [comment]
[Current documentation @ 9d3369e](https://github.com/cryptonative-ch/aqua-subgraph/blob/58d5cfdc566011441e4e2fcfc3a897bf57b879be/README.md)
