### ISSUE TITLE
Bug - Bulk update of `FixedPriceSaleCommitment` breaks the subgraph

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-subgraph#86]
Subgraph breaks on `NewTokenWithdraw` event. The handler is designed to update all `FixedPriceSaleCommitment.status` for the sale to `CLAIMED`

https://github.com/cryptonative-ch/aqua-subgraph/blob/ecfb6d801ae7b76b064277dc97d5cd6258125be9/src/mappings/sales/fixedPriceSale.ts#L74-L101

**Comment by rossneilson** [comment]
The temporary fix for this deployed to aqua-xdai-next by Adam is below:
![paste](https://user-images.githubusercontent.com/39137239/127869852-8f78b9f3-b081-40ce-8d9e-7cd8537591f1.png)

**Comment by adamazad** [comment]
Closed via #89
